on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'ArduRacerFx'
          path: /artifacts
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: /artifacts
