on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'ArduRacerFx'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ArduRacerFx
