on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        name: Download Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        id: download
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts
